config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :graduates do
    collection do
      get 'get_grad'
      get 'search_graduates'
      post 'like_employer'
      post 'unlike_employer'
    end
  end
  resources :employers do
    collection do
      get 'employer_search'
      get 'get_empl'
    end
    resources 'locations' do
      resources 'job_listings'
    end
  end
  resources 'job_listings' do
    collection do
      get 'search_job_listings'
    end
  end
  resources 'messages' do
    collection do
      get 'unread_messages'
    end
    member do
      patch 'viewed'
    end
  end

  root 'welcome#index'

end

app/models/graduate.rb
class Graduate < ActiveRecord::Base
  has_one :user, as: :userable
  has_many :links
  has_many :experiences
  has_many :educations
  before_create :assign_region
  accepts_nested_attributes_for :links
  accepts_nested_attributes_for :educations
  accepts_nested_attributes_for :experiences

  def favorited_employers
    u = self.user
    f = GradEmplFavorite.where('graduate_id = ?', u.id)
    r = []
    f.each do |favorite|
      r.push(Employer.find(favorite.employer_id))
    end
    return r
  end

  REGIONS = {
    west: [
      'CO',
      'WY',
      'MT',
      'ID',
      'WA',
      'OR',
      'UT',
      'NV',
      'CA',
      'AK',
      'HI'
    ],
    southwest:[
      'TX',
      'OK',
      'NM',
      'AZ'
    ],
    northeast:[
      'ME',
      'MA',
      'RI',
      'CT',
      'NH',
      'VT',
      'NY',
      'PA',
      'NJ',
      'DE',
      'MD'
    ],
    southeast:[
      'WV',
      'VA',
      'KY',
      'TN',
      'NC',
      'SC',
      'GA',
      'AL',
      'MS',
      'AR',
      'LA',
      'FL'
    ],
    midwest: [
      'OH',
      'IN',
      'MI',
      'IL',
      'MO',
      'WI',
      'MN',
      'IA',
      'KS',
      'NE',
      'SD',
      'ND'
    ]
  }


  def check_region
    REGIONS.each{|key, value|
      return key.to_s if value.include?(self.present_state)
    }
  end

  def assign_region
    self.present_region = self.check_region
  end

  # def link_assignment(link)
  #   new_link = Link.new
  #   new_link.url = link[:url]
  #   self.links = [new_link]
  #   new_link.save
  # end

  # def user_assignment
  #   self.user = current_user
  #   self.email = current_user.email
  # end

  # def education_assignment(education)
  #   top_education = Education.new
  #   top_education.school_name = education[:school_name]
  #   top_education.concentration = education[:concentration]
  #   top_education.level = education[:level]
  #   self.educations = [top_education]
  #   top_education.save
  # end

  # def handle_side_objects(link, education)
  #   link_assignment(link)
  #   user_assignment()
  #   education_assignment(params[:education])
  #   # Handle Portfolio Link
  #   # Handle User Logic
  #   # Handle Education
  # end

  include Workflow

  workflow do
    state :opened do
      event :restrict, transitions_to: :restricted
      event :close, transitions_to: :closed
      event :limit, transitions_to: :limited
    end

    state :restricted do
      event :open, transitions_to: :opened
    end

    state :limited do
      event :open, transitions_to: :opened
      event :restrict, transitions_to: :restricted
      event :close, transitions_to: :closed
    end

    state :closed do
      event :limit, transitions_to: :limited
      event :restrict, transitions_to: :restricted
      event :open, transitions_to: :opened
    end
  end
end

app/controllers/graduates_controller.rb
class GraduatesController < ApplicationController
  def index
    if user_signed_in?
      if current_user.userable_type == 'Admin'
        @graduates = Graduate.all
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def get_grad
    if user_signed_in?
      @graduate = Graduate.find current_user.userable_id
      @messages = Message.where('receiver_id = ?', @graduate.user.id).reverse
      @employers = @graduate.favorited_employers
    else
      @graduate = []
    end
  end

  def like_employer
    GradEmplFavorite.create({
      employer_id: params[:receiver_id],
      graduate_id: current_user.id
    })
    render nothing: true
  end

  def unlike_employer
    f = GradEmplFavorite.where('employer_id = ? AND graduate_id = ?', params[:receiver_id], current_user.id)[0]
    f.destroy
    render nothing: true
  end

  def search_graduates
    @graduates = graduate_search.reverse
  end

  def create
    @graduate = Graduate.create graduate_params
    @graduate.assign_region
    @graduate.save
    respond_to do |format|
      format.html{redirect_to graduate_path(@graduate)}
      format.json do
        handle_side_objects
        render nothing: true
      end
    end
  end

  def edit
    if user_signed_in?
      if current_user.userable_type == 'Admin'
        set_graduate
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def update
    set_graduate
    @graduate.update_attributes graduate_params
    respond_to do |format|
      format.html{redirect_to graduate_path(@graduate)}
      format.json{render nothing: true}
    end
  end

  def destroy
    set_graduate
    @graduate.destroy
    respond_to do |format|
      format.html{redirect_to graduates_path}
      format.json{render nothing: true}
    end
  end

  private
  def graduate_params
    params.require(:graduate).permit(
      :first_name,
      :last_name,
      :grad_location,
      :grad_zip,
      :grad_session,
      :grad_focus,
      :current_zip,
      :workflow_state,
      :additional_info,
      :image_url,
      :link,
      :grad_year,
      :present_city,
      :present_state,
      :email,
      :title,
      :phone,
      links_attributes: [:id, :url, :description, :graduate_id, :_destroy],
      experiences_attributes: [:id, :company, :description, :position, :graduate_id, :_destroy],
      educations_attributes: [:id, :school_name, :start_date, :end_date, :concentration, :graduate_id]
      )
  end

  def simple_graduate_search(graduate)
    return graduate.where("first_name LIKE ? OR last_name LIKE ? OR grad_focus LIKE ? OR grad_session LIKE ? OR grad_year LIKE ? OR grad_location LIKE ?", "%#{params[:input]}%", "%#{params[:input]}%", "%#{params[:input]}%", "%#{params[:input]}%", "%#{params[:input]}%", "%#{params[:input]}%")
  end

  def advanced_graduate_search(graduates)
     results = []
     graduates.each do |graduate|
      if graduate.grad_year == params[:tiy_year] || !params[:tiy_year]
        if graduate.grad_focus == params[:type] || !params[:type]
          if graduate.grad_location == params[:tiy_location] || !params[:tiy_location]
            if graduate.present_region == params[:current_location] || !params[:current_location]
               results.push(graduate)
            end
          end
        end
      end
    end
    return results
  end

  def get_favorites
    f = GradEmplFavorite.where('graduate_id = ?', current_user.id)
    r = []
    f.each do |favorite|
      r.push(Employer.find(favorite.employer_id).name)
    end
    return r
  end

  def graduate_search
    g = simple_graduate_search(Graduate)
    if params[:tiy_year] || params[:type] || params[:tiy_location] || params[:current_location]
      g = advanced_graduate_search(g)
    end
    return g
  end

  def handle_side_objects
    the_link = Link.new
    the_link.url = params[:link][:url]
    @graduate.links = [the_link]
    if user_signed_in?
      @graduate.user = current_user
    end
    top_education = Education.new
    top_education.school_name = params[:education][:school_name]
    top_education.concentration = params[:education][:concentration]
    top_education.level = params[:education][:level]
    @graduate.educations = [top_education]
    top_education.save
  end

  def set_graduate
    @graduate = Graduate.find params[:id]
  end
end

app/helpers/graduates_helper.rb
module GraduatesHelper
end

app/views/graduates/_form.html.haml
= nested_form_for [@graduate] do |f|
  = f.label :first_name
  = f.text_field :first_name
  %br/
  = f.label :last_name
  = f.text_field :last_name
  %br/
  = f.label :grad_city
  = f.text_field :grad_city
  %br/
  = f.label :grad_state
  = f.text_field :grad_state
  %br/
  = f.label :grad_focus
  = f.text_field :grad_focus
  %br/
  = f.label :grad_date
  = f.text_field :grad_date
  %br/
  = f.label :current_location
  = f.text_field :current_location
  %br/
  = f.label :additional_info
  = f.text_area :additional_info
  %br/
  = f.label :image_url
  = f.text_field :image_url
  %br/
  = f.fields_for :links do |link_form|
    = link_form.label :url
    = link_form.text_field :url
    %br/
    = link_form.label :description
    = link_form.text_area :description
    %br/
    = link_form.link_to_remove "Remove"
    %br/
  = f.link_to_add "Add a link", :links
  %br/
  = f.fields_for :experiences do |exp_form|
    = exp_form.label :company
    = exp_form.text_field :company
    %br/
    = exp_form.label :position
    = exp_form.text_field :position
    %br/
    = exp_form.label :description
    = exp_form.text_area :description
    %br/
    = exp_form.link_to_remove "Remove"
    %br/
  = f.link_to_add "Add an experience", :experiences
  %br/
  = f.fields_for :educations do |edu_form|
    = edu_form.label :school_name
    = edu_form.text_field :school_name
    %br/
    = edu_form.label :start_date
    = edu_form.text_field :start_date
    %br/
    = edu_form.label :end_date
    = edu_form.text_field :end_date
    %br/
    = edu_form.label :concentration
    = edu_form.text_field :concentration
    %br/
    = edu_form.link_to_remove "Remove"
    %br/
  = f.link_to_add "Add an education", :educations
  %br/
  = f.submit

app/views/graduates/edit.html.haml
= render 'form'

app/views/graduates/index.html.haml
.row.admin-panel
  .columns.small-12
    - @graduates.each do |grad|
      = grad.first_name
      = grad.last_name
      %br/
      = grad.grad_location
      %br/
      = grad.grad_session
      %br/
      = link_to "Edit", edit_graduate_path(grad)
      %br/

app/views/graduates/new.html.haml
= render 'form'

app/views/graduates/show.html.haml
= image_tag(@graduate.image_url)
%br/
= @graduate.first_name
= @graduate.last_name
%br/
= @graduate.grad_city
= @graduate.grad_state
%br/
= @graduate.grad_date
%br/
= @graduate.grad_focus
%br/
= @graduate.current_location
%br/
= @graduate.workflow_state
%br/
= @graduate.additional_info
%br/
- @graduate.links.each do |link|
  = link_to link.description, link.url
  %br/
- @graduate.experiences.each do |experience|
  = experience.company
  = experience.position
  %br/
  = experience.description
- @graduate.educations.each do |education|
  = education.school_name
  %br/
  = education.start_date
  = education.end_date
  %br/
  = education.concentration
  %br/
= link_to "Edit", edit_graduate_path(@graduate)
|
= link_to "Delete", graduate_path(@graduate), method: :delete