config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :graduates do
    collection do
      get 'get_grad'
      get 'search_graduates'
      post 'like_employer'
      post 'unlike_employer'
    end
  end
  resources :employers do
    collection do
      get 'employer_search'
      get 'get_empl'
    end
    resources 'locations' do
      resources 'job_listings'
    end
  end
  resources 'job_listings' do
    collection do
      get 'search_job_listings'
    end
  end
  resources 'messages' do
    collection do
      get 'unread_messages'
    end
    member do
      patch 'viewed'
    end
  end

  root 'welcome#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_one :user, as: :userable
  has_many :locations, dependent: :destroy
  geocoded_by :full_street_address
  after_validation :geocode

  def graduate_favorites
    u = self.user
    f = GradEmplFavorite.where('employer_id = ?', u.id)
    r = []
    f.each do |favorite|
      g = Graduate.find(favorite.employer_id)
      r.push("#{g.first_name} #{g.last_name}")
    end
    return r
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :update, :edit, :destroy]

  def index
    if user_signed_in?
      if current_user.userable_type == 'Admin'
        @employers = Employer.all
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def show
    if user_signed_in?
      if current_user.userable_type == 'Admin'
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def employer_search
    @employers = search_employers(params).reverse
    respond_to do |format|
      format.json
      format.html
    end
  end

  def get_empl
    if user_signed_in?
      @employer = Employer.find current_user.userable_id
      @messages = Message.where('receiver_id = ?', @employer.id)
    else
      @employer = []
    end
  end

  def create
    p params
    @employer = Employer.create employer_params
    @employer.full_street_address = "#{params[:employer][:address]}, #{params[:employer][:city]}, #{params[:employer][:state]} #{params[:employer][:zip]}"
    @employer.user = current_user
    @employer.save
    respond_to do |format|
      format.html{redirect_to employers_path}
      format.json{
        render nothing: true
      }
    end
  end

  def edit
    if user_signed_in?
      if current_user.userable_type == 'Admin'
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def update
    respond_to do |format|
      format.html{
        if user_signed_in?
          if current_user.userable_type == 'Admin'
            @employer.update_attributes employer_params
            redirect_to employers_path
          end
        end
      }
      format.json{
        @employer.update_attributes employer_params
        render nothing: true
      }
    end
  end

  def destroy
    @employer.destroy
    respond_to do |format|
      format.html{redirect_to employers_path}
      format.json{render nothing: true}
    end
  end

private



  def set_employer
    @employer = Employer.find params[:id]
  end

  def employer_params
    params.require(:employer).permit(
      :name,
      :industry,
      :founded,
      :size,
      :city,
      :state,
      :zip,
      :image_url,
      :motto,
      :culture_statement,
      :email,
      :address,
      :phone
    )
  end

  def search_employers(input)
    e = simple_employer_search(input)
    if input[:location] || input[:industry]
      e = advanced_employer_search(e, input)
    end
    return e
  end


  def simple_employer_search(input)
    return Employer.where("name LIKE ? OR industry LIKE ? OR city LIKE ? OR state LIKE ? OR zip LIKE ?", "%#{input[:input]}%", "%#{input[:input]}%", "%#{input[:input]}%", "%#{input[:input]}%", "%#{input[:input]}%")
  end


  def advanced_employer_search(employers, input)
    results = []
    employers.each do |employer|
      # if employer_location_check(employer, input[:location]) || !input[:location]
        if employer.industry == input[:industry] || !input[:industry]
          results.push(employer)
        end
      # end
    end
    return results
  end

  def employer_location_check(employer, region)
    employer.locations.each do |location|
      return true if location.region == region
    end
    return false
  end
end

app/helpers/employers_helper.rb
module EmployersHelper
  def favorited(employer, user)
    return true if GradEmplFavorite.where('employer_id = ? AND graduate_id = ?', employer.id, user.id).length > 0
    return false
  end
end

app/views/employers/_form.html.haml
= form_for(@employer) do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :industry
  = f.text_field :industry
  %br/
  = f.label :founded
  = f.text_field :founded
  %br/
  = f.label :size
  = f.text_field :size
  %br/
  = f.label :city
  = f.text_field :city
  %br/
  = f.label :state
  = f.text_field :state
  %br/
  = f.label :zip
  = f.text_field :zip
  %br/
  = f.label :image_url
  = f.text_field :image_url
  %br/
  = f.submit

app/views/employers/edit.html.haml
= render "form"

app/views/employers/index.html.haml
.row.admin-panel
  .columns.small-12  
    = link_to "New Employer", new_employer_path
    %br/
    - @employers.each do |employer|
      = employer.name
      %br/
      = employer.industry
      %br/
      = employer.founded
      %br/
      = employer.size
      %br/
      = employer.city
      %br/
      = employer.state
      %br/
      = employer.zip
      %br/
      = image_tag(employer.image_url)
      %br/
      = link_to "Show", employer_path(employer)
      %br/

app/views/employers/new.html.haml
= render "form"

app/views/employers/show.html.haml
= image_tag(@employer.image_url)
%br/
= @employer.name
%br/
= @employer.industry
%br/
= @employer.founded
%br/
= @employer.size
%br/
= @employer.city
%br/
= @employer.state
%br/
= @employer.zip
%br/
= link_to "See Locations", employer_locations_path(@employer)
|
= link_to "Edit", edit_employer_path(@employer)
|
= link_to "Delete", employer_path(@employer), method: :delete