config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :graduates do
    collection do
      get 'get_grad'
      get 'search_graduates'
      post 'like_employer'
      post 'unlike_employer'
    end
  end
  resources :employers do
    collection do
      get 'employer_search'
      get 'get_empl'
    end
    resources 'locations' do
      resources 'job_listings'
    end
  end
  resources 'job_listings' do
    collection do
      get 'search_job_listings'
    end
  end
  resources 'messages' do
    collection do
      get 'unread_messages'
    end
    member do
      patch 'viewed'
    end
  end

  root 'welcome#index'

end

app/models/job_listing.rb
class JobListing < ActiveRecord::Base
  belongs_to :location
end

app/controllers/job_listings_controller.rb
class JobListingsController < ApplicationController
  before_action :set_employer
  before_action :set_location
  before_action :set_job_listing, only: [:show, :update, :edit, :destroy]
  def index
    @job_listings = JobListing.all
  end

  def create
    @job_listing = @location.job_listings.create job_listing_params
    respond_to do |format|
      format.html{redirect_to employer_location_job_listings_path(@employer, @location)}
      format.json{render nothing: true}
    end 
  end

  def search_job_listings
    @job_listings = job_search(params)
    respond_to do |format|
      format.json
      format.html
    end
  end

  def update
    @job_listing.update_attributes job_listing_params
    respond_to do |format|
      format.html{redirect_to employer_location_job_listings_path(@employer, @location)}
      format.json{render nothing: true}
    end 
  end

  def destroy
    @job_listing.destroy
    respond_to do |format|
      format.html{redirect_to employer_location_job_listings_path(@employer, @location)}
      format.json{render nothing: true}
    end 
  end

  private
  def job_search(input)
    j = simple_job_search(input)
    if input[:type] || input[:industry] || input[:location]
      j = advanced_job_search(j, input)
    end
    return j.uniq
  end

  def simple_job_search(input)
    r = []
    r.push(JobListing.where("name LIKE ? OR position LIKE ? OR description LIKE ? OR post_date LIKE ?", "%#{input[:input]}%", "%#{input[:input]}%", "%#{input[:input]}%", "%#{input[:input]}%"))
    r.push(employer_check(input[:input]))
    r.push(location_check(input[:input]))
    return r.flatten
  end

  def location_check(input)
    l = Location.where("region LIKE ?", "%#{input}%")
    r = []
    l.each do |location|
      r.push(location.job_listings)
    end
    return r.flatten
  end

  def employer_check(input)
    r = []
    e = Employer.where('industry LIKE ?', "%#{input}%")
    e.each do |employer|
      employer.locations.each do |location|
        r.push(location.job_listings)
      end
    end
    return r.flatten
  end

  def advanced_job_search(jobs, input)
    r = []
    jobs.each do |job|
      if job.location.employer.industry == input[:industry] || !input[:industry]
        if job.location.region == input[:location] || !input[:location]
          r.push(job)
        end
      end
    end
    return r
  end

  # input
  # type(focus)
  # industry
  # region

  def set_employer
    if params[:employer_id]
      @employer = Employer.find params[:employer_id]
    end
  end

  def set_location
    if params[:location_id]
      @location = Location.find params[:location_id]
    end
  end

  def set_job_listing
    @job_listing = JobListing.find params[:id]
  end

  def job_listing_params
    params.require(:job_listing).permit(
      :name,
      :position,
      :description,
      :post_date
    )
  end
end

app/helpers/job_listings_helper.rb
module JobListingsHelper
end

app/views/job_listings/_form.html.haml
= form_for [@employer, @location, @job_listing] do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :position
  = f.text_field :position
  %br/
  = f.label :description
  = f.text_area :description
  %br/
  = f.label :post_date
  = f.text_area :post_date
  %br/
  = f.submit

app/views/job_listings/edit.html.haml
= render "form"

app/views/job_listings/index.html.haml
- if params[:location_id]
  = link_to "New job listing", new_employer_location_job_listing_path(@employer, @location)
%br/

- @job_listings.each do |listing|
  = listing.name
  %br/
  = listing.position
  %br/
  = listing.description
  %br/
  = listing.post_date
  %br/
  %br/
  - if params[:location_id]
    = link_to "Show", employer_location_job_listing_path(@employer, @location, listing)

app/views/job_listings/new.html.haml
= render "form"

app/views/job_listings/show.html.haml
= @job_listing.name
%br/
= @job_listing.position
%br/
= @job_listing.post_date
%br/
= @job_listing.description
%br/
= link_to "Edit", edit_employer_location_job_listing_path(@employer, @location, @job_listing)
|
= link_to "Destroy", employer_location_job_listing_path(@employer, @location, @job_listing), method: :delete