config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :graduates do
    collection do
      get 'get_grad'
      get 'search_graduates'
      post 'like_employer'
      post 'unlike_employer'
    end
  end
  resources :employers do
    collection do
      get 'employer_search'
      get 'get_empl'
    end
    resources 'locations' do
      resources 'job_listings'
    end
  end
  resources 'job_listings' do
    collection do
      get 'search_job_listings'
    end
  end
  resources 'messages' do
    collection do
      get 'unread_messages'
    end
    member do
      patch 'viewed'
    end
  end

  root 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :employer
  has_many :job_listings, dependent: :destroy

  before_create :assign_region

  REGIONS = {
    west: [
      'CO',
      'WY',
      'MT',
      'ID',
      'WA',
      'OR',
      'UT',
      'NV',
      'CA',
      'AK',
      'HI'
    ],
    southwest:[
      'TX',
      'OK',
      'NM',
      'AZ'
    ],
    northeast:[
      'ME',
      'MA',
      'RI',
      'CT',
      'NH',
      'VT',
      'NY',
      'PA',
      'NJ',
      'DE',
      'MD'
    ],
    southeast:[
      'WV',
      'VA',
      'KY',
      'TN',
      'NC',
      'SC',
      'GA',
      'AL',
      'MS',
      'AR',
      'LA',
      'FL'
    ],
    midwest: [
      'OH',
      'IN',
      'MI',
      'IL',
      'MO',
      'WI',
      'MN',
      'IA',
      'KS',
      'NE',
      'SD',
      'ND'
    ]
  }


  def check_region
    REGIONS.each do |key, value|
      return key.to_s if value.include?(self.state)
    end
  end

  def assign_region
    self.region = self.check_region
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= form_for [@employer, @location] do |f|
  = f.label :city
  = f.text_field :city
  %br/
  = f.label :state
  = f.text_field :state
  %br/
  = f.label :zip
  = f.text_field :zip
  %br/
  = f.label :description
  = f.text_area :description
  %br/
  = f.submit

app/views/locations/index.html.haml
= link_to "New Location for #{@employer.name}", new_employer_location_path(@employer)
- @locations.each do |location|
  = location.city
  %br/
  = location.state
  %br/
  = location.zip
  %br/
  = location.description
  %br/
  = link_to "Show", employer_location_path(@employer, location)

app/views/locations/new.html.haml
= render "form"

app/views/locations/show.html.haml
= @location.city
%br/
= @location.state
%br/
= @location.zip
%br/
= @location.description
%br/
= link_to "Edit", edit_employer_location_path(@employer, @location)
|
= link_to "Delete", employer_location_path(@employer, @location), method: :delete
|
= link_to "Job Listings", employer_location_job_listings_path(@employer, @location)